### ISSUE TITLE
Rolling back sometimes panics

### ISSUE THREAD

**Issue by graup** [aergoio/aergo-esindexer#1]
```
{"level":"warn","module":"esindexer","error":"elastic: Error 409 (Conflict)","time":"2018-12-26T09:11:53Z","message":"Failed to delete blocks"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x9e59d1]

goroutine 55 [running]:
github.com/aergoio/aergo-esindexer/esindexer.(*EsIndexer).DeleteBlocksInRange(0xc0000fe280, 0x4cd, 0x5d8)
	/go/src/github.com/aergoio/aergo-esindexer/esindexer/esindexer.go:371 +0x4a1
github.com/aergoio/aergo-esindexer/esindexer.(*EsIndexer).SyncBlock(0xc0000fe280, 0xc0003e5900)
	/go/src/github.com/aergoio/aergo-esindexer/esindexer/esindexer.go:240 +0xfb
github.com/aergoio/aergo-esindexer/esindexer.(*EsIndexer).StartStream.func1(0xc0000fe280)
	/go/src/github.com/aergoio/aergo-esindexer/esindexer/esindexer.go:199 +0x36
created by github.com/aergoio/aergo-esindexer/esindexer.(*EsIndexer).StartStream
	/go/src/github.com/aergoio/aergo-esindexer/esindexer/esindexer.go:186 +0xeb
```

**Comment by graup** [comment]
Fixed the panic, but should continue monitoring the logs for the conflicts.
